### ISSUE TITLE
Reduce space used by nltk_data

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln-deploy#10]
I'm creating a [docker](http://docker.io) container with a complete installation of PyPLN but the image grew from 180MB (minimal Ubuntu installation) to 2.9GB! 1.9GB are from `/srv/pypln/nltk_data` and I suspect we don't need even 10% of this.
So, we need to figure out which corpora we really need with our current workers and then change the installation script to download only these corpora.
With this change we'll be able to deploy PyPLN faster on regular machines and it'll be easier/faster to share my docker container.

**Comment by turicas** [comment]
Related to https://github.com/NAMD/pypln.backend/issues/147

**Comment by fccoelho** [comment]
The corpora used should also be documented somewhere.

**Comment by turicas** [comment]
I've done this task. For more information, look at: https://github.com/NAMD/pypln.backend/issues/147

@fccoelho, it was documented on PyPLN's backend README.

Just so you know, new space used is 77 MB:

```
turicas@thinking:~/nltk_data
$ du -hsc *
1.9M    corpora
27M taggers
49M tokenizers
77M total
```
