### ISSUE TITLE
Create a Dockerfile equivalent to this fabfile

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln-deploy#12]
As we want a [Docker](http://docker.io) container with a PyPLN-demo pre-installed, the best option for us is to create a `Dockerfile` to automate the process of building a container - this way we can automatically build new containers when new versions of the software is released.

We need to use [Dockerfile`'s instructions](http://docs.docker.io/en/latest/use/builder/) to describe the whole process currently made by `fabfile.py`.

**Comment by flavioamieiro** [comment]
I'll close this for now because it is not a priority, but we can look into it later.
