### ISSUE TITLE
Migrate from Gunicorn to uWSGI (?)

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln-deploy#16]
According to [a blog post](http://blog.kgriffs.com/2012/12/18/uwsgi-vs-gunicorn-vs-node-benchmarks.html), uWSGI is way faster than Gunicorn, so we may migrate or create option to select one of each.

**Comment by flavioamieiro** [comment]
I'll close this for now because it is not a priority, but we can look into it later.
