### ISSUE TITLE
Evaluate SlapOS

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln-deploy#3]
As we have some non-pythonic dependencies, maybe [SlapOS](http://community.slapos.org/) would be a good solution for deployment process. It uses buildout and have lots of facilities on provisioning virtual machines, so it'd be a great choice also if we are thinking about automatically growing or shrinking our cluster based on demand.

Related to #2.

**Comment by flavioamieiro** [comment]
I'll close this for now because it is not a priority, but we can look into it later.
