### ISSUE TITLE
Add 'manage update_index' to crontab

### ISSUE THREAD

**Issue by turicas** [NAMD/pypln-deploy#6]
As we are using whoosh to index documents, it's needed to run a script continuously to index new documents and it needs to be added on crontab (I think every minute is fine).

**Comment by flavioamieiro** [comment]
We can run this in the [post_save signal](https://docs.djangoproject.com/en/1.4/ref/signals/#django.db.models.signals.post_save).

**Comment by fccoelho** [comment]
It would be a good idea to time the indexing after uploading the TJRJ corpus to the database.
